### PR TITLE
feat: Support workspaces

### PR DESCRIPTION
**Pull request by beyondkmp**
fix https://github.com/electron-userland/electron-builder/pull/7774

### CODE REVIEW

**Comment by beyondkmp** [comment]
All unit test cases passed.
image

**Comment by beyondkmp** [comment]
@mmaietta Please help check it.

**Comment by mmaietta** [comment]
Nice work! Love that you got all the tests passing

**Comment by mmaietta** [comment]
@beyondkmp can you open this PR against https://github.com/develar/app-builder?

I can't seem to resolve the merge conflicts on getting my `master` branch on `develar/app-builder` repo. I have write-access to the repo now, and the test infrastructure is already set up, along with changeset versioning automation

**Pull request merged**
